ftplugin-dir: ~/.config/nvim/ftplugin
plugins:
  - javascript:
    - cmd: js-beautify
      arg:
  - python:
    - cmd: yapf
      arg:
  - haskell:
    - cmd: ormolu
      arg:
    - cmd: brittany
      arg: --columns 80 --indent 2
    - cmd: hindent
      arg: --indent-size 2 --line-length 80
  - nix:
    - cmd: nixpkgs-fmt
      arg:
  - purescript:
    - cmd: purty
      arg: "- --write"
