- include: check-fact-template.yml
  with_items:
    - '{{ dir_public }}'
    - '{{ dir_temp }}'
    - '{{ configs_dir }}'
    - '{{ personal_cloud_dir }}'
    - '{{ personal_cloud_app_dir }}'
    - '{{ personal_local_private_dir }}'
