# usage: ansible-playbook system-chooser.yml -i ansible_hosts --ask-become-pass

- name: system-chooser
  hosts: all
  tasks:
    - set_fact: configs_dir="{{ ansible_env.HOME }}/configs-and-scripts/configs"
    - set_fact: dir_neovim="{{ ansible_env.HOME }}/.config/nvim"

    - set_fact: dir_sync="{{ ansible_env.HOME }}/Sync"

    - set_fact: dir_personal_cloud="{{ dir_sync }}/Personal-Cloud"
    - set_fact: dir_personal_cloud_app="{{ dir_sync }}/Personal-Cloud/App"
    - set_fact: dir_personal_local_private="{{ dir_sync }}/Personal-Local/Private"
    - set_fact: dir_public="{{ dir_sync }}/Public"
    - set_fact: dir_temp="{{ dir_sync }}/Temp"

    - import_tasks: playbook/task/check-fact.yml
#
# - import_playbook: systems/nixos.yml
- import_playbook: systems/debian.yml
# - import_playbook: systems/fedora.yml
