- name: configs -> symlink .bashrc
  ansible.builtin.file:
    src: "{{ configs_dir }}/bash/nixos.bashrc"
    dest: "{{ ansible_env.HOME }}/.bashrc"
    state: link
    force: yes

- name: configs -> create .xinitrc symlink
  ansible.builtin.file:
    src: "{{ configs_dir }}/xorg/nixos.xinitrc"
    dest: "{{ ansible_env.HOME }}/.xinitrc"
    state: link
    force: yes
