- include: ../../task-template/nix-singleuser-install.yml
  vars:
    packages:
      - cmus
      - dejsonlz4
      - du-dust
      - gdrive
      - okular
      - scrot
      - stack
      - telegram-desktop
      - tor-browser-bundle-bin
      - vim_configurable
      - vlc
      - vscodium
      - xmobar
      - xmonad-with-packages
