- name: package-nix -> gather list of installed packages
  shell: nix-env -q
  register: nix_pkgs_installed

- name: package-nix -> install only new packages
  ansible.builtin.shell: 'nix-env -i {{ item }}'
  when: not nix_pkgs_installed.stdout is search(item)
  with_items:
    - cmus
    - dejsonlz4
    - du-dust
    - gdrive
    - okular
    - stack
    - telegram-desktop
    - vim_configurable
    - vlc
    - vscodium
    - xmobar
    - xmonad-with-packages
