- name: unison -> create ~/.unison/ if not exist
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.unison"
    state: directory

- name: unison -> symlink default.prf
  ansible.builtin.file:
    src: "{{ configs_dir }}/unison/default.prf"
    dest: "{{ ansible_env.HOME }}/.unison/default.prf"
    state: link
