- name: w3m -> create ~/.w3m/ if not exist
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.w3m"
    state: directory

- name: w3m -> symlink keymap
  ansible.builtin.file:
    src: "{{ configs_dir }}/w3m/keymap"
    dest: "{{ ansible_env.HOME }}/.w3m/keymap"
    state: link
