- name: font -> copy Comic Shanns font to the system
  become: yes
  ansible.builtin.copy:
    src: "{{ configs_dir }}/font/comic-shanns/v2/comic shanns 2.ttf"
    dest: "/usr/local/share/fonts"

- name: font -> refresh font cache
  ansible.builtin.command: "fc-cache"
