- name: package-apt -> install packages
  become: yes
  vars:
    ansible_python_interpreter: '/usr/bin/python3'
  ansible.builtin.apt:
    name: '{{ item }}'
  with_items:
    - acpi
    - adb
    - alsa-utils
    - ansible
    - apt-file
    - bat
    - calibre
    - cmus
    - cpufrequtils
    - curl
    - dbus-x11
    - dmidecode
    - firefox-esr
    - flashrom
    - fontconfig
    - fonts-thai-tlwg-ttf
    - gcc
    - gimp
    - git
    - gpg
    - htop
    - imagemagick
    - inkscape
    - jpegoptim
    - less
    - kdenlive
    - libreoffice
    - libx11-dev
    - libxft-dev
    - libxinerama-dev
    - libxrandr-dev
    - libxss-dev
    - make
    - mc
    - mupdf
    - network-manager
    - neofetch
    - password-store
    - pinentry-gtk2
    - psmisc
    - python-is-python3
    - python3-pip
    - ranger
    - redshift
    - rfkill
    - ripgrep
    - shellcheck
    - simplescreenrecorder
    - smartmontools
    - sudo
    - telegram-desktop
    - thunar
    - tumbler
    - trash-cli
    - tree
    - unzip
    - vrms
    - weechat
    - x11-utils
    - x11-xserver-utils
    - xclip
    - xmobar
    - xmonad
    - xorg
    - yarn
