- name: alias -> create ~/.alias if not exist
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.alias"
    state: directory

- name: alias -> symlink .shared.alias
  ansible.builtin.file:
    src: "{{ configs_dir }}/alias/shared.alias"
    dest: "{{ ansible_env.HOME }}/.alias/shared.alias"
    state: link

- name: alias -> symlink .alias-modules
  ansible.builtin.file:
    src: "{{ configs_dir }}/alias/modules"
    dest: "{{ ansible_env.HOME }}/.alias/modules"
    state: link
