- name: fonts -> create ~/.local/share/fonts if not exist
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.local/share/fonts"
    state: directory

- name: fonts -> install Comic Shanns font
  ansible.builtin.copy:
    src: "{{ configs_dir }}/font/comic-shanns/v2/comic shanns 2.ttf"
    dest: "{{ ansible_env.HOME }}/.local/share/fonts"

- name: fonts -> refresh font cache
  ansible.builtin.command: "fc-cache"
