- hosts: "{{ hostvars['localhost']['hostlist'] }}"
  name: common-configs
  tasks:
    - import_tasks: task/common-configs/alias.yml
    - import_tasks: task/common-configs/alsa.yml
    - import_tasks: task/common-configs/bash.yml
    - import_tasks: task/common-configs/cmus.yml
    - import_tasks: task/common-configs/git.yml
    - import_tasks: task/common-configs/gtk-3.0.yml
    - import_tasks: task/common-configs/inkscape.yml
    - import_tasks: task/common-configs/lazyman-pomodoro.yml
    - import_tasks: task/common-configs/mc.yml
    - import_tasks: task/common-configs/newsboat.yml
    - import_tasks: task/common-configs/pass.yml
    - import_tasks: task/common-configs/ranger.yml
    - import_tasks: task/common-configs/readline.yml
    - import_tasks: task/common-configs/ssh.yml
    - import_tasks: task/common-configs/tmux.yml
    - import_tasks: task/common-configs/unison.yml
    - import_tasks: task/common-configs/w3m.yml
    - import_tasks: task/common-configs/xmobar.yml
    - import_tasks: task/common-configs/xmonad.yml
    - import_tasks: task/common-configs/xorg.yml
