- name: cmus -> create ~/.config/cmus/ if not exist
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/cmus"
    state: directory

- name: cmus -> symlink rc
  ansible.builtin.file:
    src: "{{ configs_dir }}/cmus/rc"
    dest: "{{ ansible_env.HOME }}/.config/cmus/rc"
    state: link
