- name: package-nix -> gather list of installed packages
  become: yes
  become_user: root
  become_method: su
  shell: nix-env -q
  register: nix_pkgs_installed

- name: package-nix -> install only new packages
  become: yes
  become_user: root
  become_method: su
  ansible.builtin.shell: 'nix-env -i {{ item }}'
  when: not nix_pkgs_installed.stdout is search(item)
  with_items:
    - acpi
    - alsa-utils
    - ansible
    - bat
    - calibre
    - cmus
    - cpufrequtils
    - curl
    - dejsonlz4
    - dmidecode
    - docker
    - docker-compose
    - du-dust
    - exa
    - fd
    - feh
    - firefox-esr-unwrapped
    - flashrom
    - gdrive
    - ghc
    - ghostscript
    - gimp
    - git
    - git-repo
    - gwenview
    - haskell-language-server
    - heimdall
    - htop
    - imagemagick
    - inkscape
    - jpegoptim
    - kdenlive
    - less
    - libreoffice
    - loc
    - lm-sensors
    - mc
    - mediainfo
    - mupdf
    - neomutt
    - newsboat
    - nixpkgs-fmt
    - pandoc
    - password-store
    - pencil
    - purescript
    - qview
    - ranger
    - redshift
    - ripgrep
    - rsync
    - scrot
    - shellcheck
    - simplescreenrecorder
    - smartmontools
    - spago
    - tealdeer
    - telegram-desktop
    - tmux
    - tokei
    - tor-browser-bundle-bin
    - tree
    - tumbler
    - ungoogled-chromium
    - unzip
    - vim_configurable
    - vlc
    - vscodium
    - w3m
    - weechat
    - wget
    - xmobar
    - xmonad-with-packages
    - yarn
    - zenity
    - zip
