# usage: ansible-playbook system-chooser.yml --ask-become-pass

- hosts: localhost # this need to be fixed, modify set_fact below
  name: system-chooser
  tasks:
    - set_fact: hostlist=localhost

    - set_fact: sync_dir="{{ ansible_env.HOME }}/Sync"
    - set_fact: backup_dir="{{ sync_dir }}/Backup"
    - set_fact: cloud_dir="{{ sync_dir }}/Cloud"
    - set_fact: private_dir="{{ sync_dir }}/Private"

    - set_fact: configs_dir="{{ ansible_env.HOME }}/configs-and-scripts/configs"
    - import_tasks: playbook/task/check-fact.yml
#
# - import_playbook: systems/debian.yml
# - import_playbook: systems/fedora.yml
