- hosts: all
  name: common-neovim
  tasks:
    - name: common-neovim -> create "{{ dir_neovim }}" if not exist
      ansible.builtin.file:
        path: "{{ dir_neovim }}"
        state: directory
    - name: common-neovim -> create symlink ~/.config/nvim/init.lua
      ansible.builtin.file:
        src: "{{ configs_dir }}/neovim/init.vim"
        dest: "{{ ansible_env.HOME }}/.config/nvim/init.vim"
        state: link

    - import_tasks: task/common-neovim/colors.yml
    - import_tasks: task/common-neovim/ftplugin.yml
    - import_tasks: task/common-neovim/plugin.yml
    - import_tasks: task/common-neovim/temp.yml
    - import_tasks: task/common-neovim/template.yml
