# usage ansible-playbook <this file>
---
  - name: "Clone Git Repositories"
    hosts: localhost
    connection: local
    tasks:
      - name: clone -> create Git folders if not exist
        ansible.builtin.file:
          path: "{{ item }}"
          state: directory
        with_items:
          - "{{ ansible_env.HOME }}/Git"
          - "{{ ansible_env.HOME }}/Git-Forked"

      - name: clone -> clone personal GitHub repositories
        ansible.builtin.git:
          repo: "git@github.com:tkiat/{{ item }}.git"
          dest: "{{ ansible_env.HOME }}/Git/{{ item }}"
        with_items:
          - a-freedom-blog
          - archive
          - my-writings-public
          - pomodoro-bar
          - pomodoro-bar-py
          - task
          - templates
          - terminal-game-client
          - tkiat.github.io
          - vim-autofmt-gen
          - vim-custom-theme

      - name: clone -> clone forked GitHub repositories (depth 1)
        ansible.builtin.git:
          repo: "git@github.com:tkiat/{{ item }}.git"
          dest: "{{ ansible_env.HOME }}/Git-Forked/{{ item }}"
          depth: 1
        with_items:
          - nixpkgs

      - name: clone -> clone personal GitLab repositories
        ansible.builtin.git:
          repo: "git@gitlab.com:tkiat/{{ item }}.git"
          dest: "{{ ansible_env.HOME }}/Git/{{ item }}"
        with_items:
          - assets
          - guix-channel
          - learning
          - nix-channel
          - my-writings-private

      - name: clone -> clone forked GitLab repositories
        ansible.builtin.git:
          repo: "git@gitlab.com:tkiat/{{ item }}.git"
          dest: "{{ ansible_env.HOME }}/Git-Forked/{{ item | regex_replace('^forked-(.*)$', '\\1') }}"
        with_items:
          # - forked-coreboot # submodule problem
          - forked-dmenu
          - forked-dwm
          - forked-grub
          - forked-libreboot-lbmk
          - forked-open_ath9k_htc_firmware
          - forked-slock
          - forked-st
